### PR TITLE
Gracefully handle missing IMDB ID on details page (Fixes #17)

### LINKED ISSUE #17: Freeze Kodi
Hello. I updated the metadata Kodi csfd and then I'm in trouble.
Approximately 25% of the scan hangs, slow down across the board starts and Kodi Kodi stopped working.

After uninstalling csfd metadata version 3.13 Kodi goes without problems

We tried to Kodi 17.6 Kryprton on version 18.5 Leia

Please help with the solution

Zdravím. 
Aktualizoval jsem v Kodi metadata csfd a následně mám problémy.
Zhruba v 25% se prohledávání zasekne, zpomalý celé Kodi a naskočí tabule Kodi přestal pracovat.

Po odinstalování csfd metadata verze 3.13 Kodi jede bez problémů

Vyzkoušel jsme na Kodi 17.6 Kryprton i na verzi 18.5 Leia

Prosím o pomoc s řešením

### PR DESCRIPTION
**Pull request by MrVoltz**
Prevent infinite loop caused by failed request to "http://akas.imdb.com/title//".

### CODE REVIEW

**Review by janjurca — APPROVED** [review]
I've tested the changes and it works well.

**Comment by panther7** [comment]
Please, merge this request and pls update dependency in https://github.com/kodi-czsk/repository

**Comment by panther7** [comment]
^ @ekarorgit

**Comment by ekarorgit** [comment]
thanks for the idea of handling missing imdbId, added along other changes in v 3.15 credited you in changelog.

**Pull request closed without merging**
